---
title: "ADASD package performance summary"
author: "Marcin Szymanski"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ADASD package performance summary}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```{r echo=FALSE, }
library(microbenchmark)
library(adasd, warn.conflicts = FALSE)
library(ggplot2)
```
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 1024)
```

Performance tests
===

Perms
---

```{r echo=FALSE, fig.width=8,width=8}
res <- microbenchmark(perms(1),perms(2),
                      perms(3),perms(4),
                      perms(5),perms(6),
                      perms(7),perms(8))
res
autoplot(res)
boxplot(res)
```

Comparing with  **gtools::permutations**

```{r echo=FALSE, fig.width=8,width=8}
library(gtools)
res <- microbenchmark(permutations(1,1,1:1),permutations(2,2,1:2),
                      permutations(3,3,1:3),permutations(4,4,1:4),
                      permutations(5,5,1:5),permutations(6,6,1:6))     
res
autoplot(res)
boxplot(res)
```

I feel like a winner

Mode
---

```{r echo=FALSE, fig.width=8,width=8}
res <- microbenchmark(mode(c(1:10,5)),mode(c(1:100,50)),
                      mode(c(1:1000,500)),mode(c(1:10000,5000)))
res
autoplot(res)
boxplot(res)
```

Comparing with following R solution

```{r }
mode_r <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```

```{r echo=FALSE, fig.width=8,width=8}
res <- microbenchmark(mode_r(c(1:10,5)),mode_r(c(1:100,50)),
                      mode_r(c(1:1000,500)),mode_r(c(1:10000,5000)))
res
autoplot(res)
boxplot(res)
```

Faster again? Impossible

Shortestpath
---

Test data

```{r echo=FALSE}
G2 <- matrix(rep(1,4),nrow=2)
print("G2")
G2
G10 <- matrix(rep(1,100),nrow=10)
print("G10 - 10*10 matrix all 1")
G50 <- matrix(rep(1,2500),nrow=50)
print("G50 - 50*50 matrix all 1")
G100 <- matrix(rep(1,10000),nrow=100)
print("G100 - 100*100 matrix all 1")
G1000 <- matrix(rep(1,1000000),nrow=1000)
print("G1000 - 1000*1000 matrix all 1")
G2000 <- matrix(rep(1,4000000),nrow=2000)
print("G1000 - 2000*2000 matrix all 1")
  
```

```{r echo=FALSE, fig.width=8,width=8}
res <- microbenchmark(shortestpath(G2,1,2),shortestpath(G10,1,10),
                      shortestpath(G50,1,50),shortestpath(G100,1,100),
                      shortestpath(G1000,1,1000),shortestpath(G2000,1,2000))
res
autoplot(res)
boxplot(res)
```

Comparing with  igraph::shortest.paths

```{r echo=FALSE, fig.width=8,width=8}
library(igraph)
G2 <- graph.full(2,loops=TRUE)
G10 <- graph.full(10,loops=TRUE)
G50 <- graph.full(50,loops=TRUE)
G100 <- graph.full(100,loops=TRUE)
G1000 <- graph.full(1000,loops=TRUE)
G2000 <- graph.full(2000,loops=TRUE)
G_sp <-function(G,n) {
  shortest.paths(G,V(G)[1],V(G)[n],mode="out",algorithm="dijkstra")
  }
res <- microbenchmark(G_sp(G2,2),G_sp(G10,10),
                      G_sp(G50,50),G_sp(G100,100),
                      G_sp(G1000,1000),G_sp(G2000,2000))
res
autoplot(res)
boxplot(res)
```

Initially faster, later slower :/