# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mode
#' @description
#' \code{mode} returns the most frequent value of an integer vector
#' 
#' @param x - An integer vector
#' 
#' @examples
#' mode(c(1,2,2))
#' 
#' @return Most frequent value of \code{x}
#' 
#' @export
mode <- function(x) {
    .Call('adasd_mode', PACKAGE = 'adasd', x)
}

#' @title Perms
#' @description
#' \code{perms} returns all permutations of set {1,2,..,n}
#' 
#' @param n - integer 
#' 
#' @examples
#' perms(2)
#' 
#' @return \code{IntegerArray(n!,n)} containing all permutations
#' 
#' @export
perms <- function(n) {
    .Call('adasd_perms', PACKAGE = 'adasd', n)
}

#' @title Shortest path
#' @description
#' \code{shortestpath} is an implementation of Dijkstra's algorithm to compute
#' the length of the shortest path between vertices \code{x} and \code{j} represented 
#' by 0-1 matrix \code{G}
#' @param G - \code{n*n} matrix with values in \{0,1\} 
#' @param x - An integer number of starting vertex
#' @param y - An integer number of ending vector
#' 
#' @examples
#' shortestpath(matrix(c(0,1,0,0),nrow=2),1,2)
#' 
#' @return Length of the longest path or 999999999 if there is no path between vertices
#' 
#' @export
shortestpath <- function(G, x, y) {
    .Call('adasd_shortestpath', PACKAGE = 'adasd', G, x, y)
}

